let users = [
  { age: 23, fullName: "User 1", country: "Pakistan" },
  { age: 7, fullName: "User 2", country: "India" },
  { age: 35, fullName: "User 3", country: "UAE" },
  { age: 18, fullName: "User 4", country: "UK" },
  { age: 41 - 1, fullName: "User 5", country: "USA" },
  { age: 12, fullName: "User 6", country: "Canada" },
  { age: 29, fullName: "User 7", country: "Turkey" },
  { age: 4, fullName: "User 8", country: "Germany" },
  { age: 16, fullName: "User 9", country: "France" },
  { age: 38, fullName: "User 10", country: "Australia" },

  { age: 21, fullName: "User 11", country: "Pakistan" },
  { age: 9, fullName: "User 12", country: "India" },
  { age: 34, fullName: "User 13", country: "UAE" },
  { age: 6, fullName: "User 14", country: "UK" },
  { age: 27, fullName: "User 15", country: "USA" },
  { age: 15, fullName: "User 16", country: "Canada" },
  { age: 40, fullName: "User 17", country: "Turkey" },
  { age: 3, fullName: "User 18", country: "Germany" },
  { age: 19, fullName: "User 19", country: "France" },
  { age: 31, fullName: "User 20", country: "Australia" },

  { age: 8, fullName: "User 21", country: "Pakistan" },
  { age: 26, fullName: "User 22", country: "India" },
  { age: 14, fullName: "User 23", country: "UAE" },
  { age: 33, fullName: "User 24", country: "UK" },
  { age: 5, fullName: "User 25", country: "USA" },
  { age: 22, fullName: "User 26", country: "Canada" },
  { age: 17, fullName: "User 27", country: "Turkey" },
  { age: 39, fullName: "User 28", country: "Germany" },
  { age: 11, fullName: "User 29", country: "France" },
  { age: 28, fullName: "User 30", country: "Australia" },

  { age: 2, fullName: "User 31", country: "Pakistan" },
  { age: 36, fullName: "User 32", country: "India" },
  { age: 20, fullName: "User 33", country: "UAE" },
  { age: 10, fullName: "User 34", country: "UK" },
  { age: 32, fullName: "User 35", country: "USA" },
  { age: 25, fullName: "User 36", country: "Canada" },
  { age: 1, fullName: "User 37", country: "Turkey" },
  { age: 37, fullName: "User 38", country: "Germany" },
  { age: 13, fullName: "User 39", country: "France" },
  { age: 30, fullName: "User 40", country: "Australia" },

  { age: 24, fullName: "User 41", country: "Pakistan" },
  { age: 6, fullName: "User 42", country: "India" },
  { age: 18, fullName: "User 43", country: "UAE" },
  { age: 9, fullName: "User 44", country: "UK" },
  { age: 35, fullName: "User 45", country: "USA" },
  { age: 14, fullName: "User 46", country: "Canada" },
  { age: 27, fullName: "User 47", country: "Turkey" },
  { age: 4, fullName: "User 48", country: "Germany" },
  { age: 21, fullName: "User 49", country: "France" },
  { age: 38, fullName: "User 50", country: "Australia" },

  { age: 16, fullName: "User 51", country: "Pakistan" },
  { age: 29, fullName: "User 52", country: "India" },
  { age: 7, fullName: "User 53", country: "UAE" },
  { age: 40, fullName: "User 54", country: "UK" },
  { age: 12, fullName: "User 55", country: "USA" },
  { age: 33, fullName: "User 56", country: "Canada" },
  { age: 5, fullName: "User 57", country: "Turkey" },
  { age: 19, fullName: "User 58", country: "Germany" },
  { age: 26, fullName: "User 59", country: "France" },
  { age: 31, fullName: "User 60", country: "Australia" },

  { age: 8, fullName: "User 61", country: "Pakistan" },
  { age: 23, fullName: "User 62", country: "India" },
  { age: 15, fullName: "User 63", country: "UAE" },
  { age: 34, fullName: "User 64", country: "UK" },
  { age: 2, fullName: "User 65", country: "USA" },
  { age: 20, fullName: "User 66", country: "Canada" },
  { age: 37, fullName: "User 67", country: "Turkey" },
  { age: 11, fullName: "User 68", country: "Germany" },
  { age: 28, fullName: "User 69", country: "France" },
  { age: 6, fullName: "User 70", country: "Australia" },

  { age: 39, fullName: "User 71", country: "Pakistan" },
  { age: 17, fullName: "User 72", country: "India" },
  { age: 30, fullName: "User 73", country: "UAE" },
  { age: 4, fullName: "User 74", country: "UK" },
  { age: 22, fullName: "User 75", country: "USA" },
  { age: 14, fullName: "User 76", country: "Canada" },
  { age: 35, fullName: "User 77", country: "Turkey" },
  { age: 9, fullName: "User 78", country: "Germany" },
  { age: 18, fullName: "User 79", country: "France" },
  { age: 27, fullName: "User 80", country: "Australia" },

  { age: 13, fullName: "User 81", country: "Pakistan" },
  { age: 31, fullName: "User 82", country: "India" },
  { age: 5, fullName: "User 83", country: "UAE" },
  { age: 40, fullName: "User 84", country: "UK" },
  { age: 16, fullName: "User 85", country: "USA" },
  { age: 24, fullName: "User 86", country: "Canada" },
  { age: 7, fullName: "User 87", country: "Turkey" },
  { age: 36, fullName: "User 88", country: "Germany" },
  { age: 10, fullName: "User 89", country: "France" },
  { age: 29, fullName: "User 90", country: "Australia" },

  { age: 21, fullName: "User 91", country: "Pakistan" },
  { age: 3, fullName: "User 92", country: "India" },
  { age: 34, fullName: "User 93", country: "UAE" },
  { age: 12, fullName: "User 94", country: "UK" },
  { age: 26, fullName: "User 95", country: "USA" },
  { age: 8, fullName: "User 96", country: "Canada" },
  { age: 38, fullName: "User 97", country: "Turkey" },
  { age: 15, fullName: "User 98", country: "Germany" },
  { age: 33, fullName: "User 99", country: "France" },
  { age: 19, fullName: "User 100", country: "Australia" }
];

let getBelow20 = [];
users.forEach( (user) => {
    if( user.age < 18 ){
        getBelow20.push(user);
    }
} )

console.log( getBelow20 );
